ALTER TABLE lessons ADD COLUMN content_format VARCHAR(20) NOT NULL DEFAULT 'TEXT';
ALTER TABLE lessons ADD COLUMN video_url VARCHAR(500);
CREATE TABLE lesson_resources (
    resource_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lesson_id INTEGER NOT NULL REFERENCES lessons(lesson_id) ON DELETE CASCADE,
    name VARCHAR(160) NOT NULL,
    media_type VARCHAR(80) NOT NULL,
    file_size INTEGER NOT NULL,
    content BYTEA NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_lesson_resources ON lesson_resources(lesson_id, resource_id);
