ALTER TABLE lessons ADD COLUMN content_revision INTEGER NOT NULL DEFAULT 0;
CREATE TABLE lesson_drafts (
    draft_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id INTEGER NOT NULL REFERENCES courses(course_id) ON DELETE CASCADE,
    owner_id INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    lesson_id INTEGER REFERENCES lessons(lesson_id) ON DELETE CASCADE,
    lesson_key INTEGER NOT NULL,
    revision INTEGER NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    base_revision INTEGER,
    title VARCHAR(255), order_index INTEGER, content_url VARCHAR(500),
    text_content TEXT, content_format VARCHAR(20), video_url VARCHAR(500),
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_lesson_draft UNIQUE(course_id, owner_id, lesson_key),
    CONSTRAINT ck_lesson_draft_key CHECK ((lesson_id IS NULL AND lesson_key = 0) OR lesson_key = lesson_id)
);
CREATE TABLE lesson_content_versions (
    version_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lesson_id INTEGER NOT NULL REFERENCES lessons(lesson_id) ON DELETE CASCADE,
    revision INTEGER NOT NULL, editor_id INTEGER NOT NULL REFERENCES users(user_id),
    title VARCHAR(255) NOT NULL, order_index INTEGER NOT NULL, content_url VARCHAR(500),
    text_content TEXT, content_format VARCHAR(20), video_url VARCHAR(500),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_lesson_version UNIQUE(lesson_id, revision)
);
