CREATE TABLE question_replies (
    reply_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id INTEGER NOT NULL REFERENCES lesson_questions(question_id) ON DELETE CASCADE,
    author_id INTEGER NOT NULL REFERENCES users(user_id),
    author_role VARCHAR(20) NOT NULL CHECK (author_role IN ('STUDENT', 'TEACHER', 'ADMIN')),
    body TEXT NOT NULL,
    is_hidden BOOLEAN NOT NULL DEFAULT FALSE,
    client_request_id VARCHAR(36),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_reply_author_request UNIQUE (author_id, client_request_id)
);
CREATE INDEX ix_reply_question_visible ON question_replies(question_id, is_hidden, reply_id DESC);

-- Preserve the existing official answer as the first message in each conversation.
INSERT INTO question_replies (question_id, author_id, author_role, body, created_at)
SELECT q.question_id, q.answered_by,
       CASE WHEN u.role = 'ADMIN' THEN 'ADMIN' ELSE 'TEACHER' END,
       q.answer, COALESCE(q.answered_at, q.created_at)
FROM lesson_questions q JOIN users u ON u.user_id = q.answered_by
WHERE q.answer IS NOT NULL AND TRIM(q.answer) <> '';
