CREATE TABLE course_wishlist (
 wishlist_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 student_id INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
 course_id INTEGER NOT NULL REFERENCES courses(course_id) ON DELETE CASCADE,
 saved_at TIMESTAMP NOT NULL,
 CONSTRAINT uq_wishlist_student_course UNIQUE (student_id, course_id)
);
CREATE INDEX ix_wishlist_student_saved ON course_wishlist(student_id, saved_at DESC, wishlist_id DESC);
CREATE INDEX ix_wishlist_course ON course_wishlist(course_id);
