ALTER TABLE courses ADD COLUMN curriculum_revision INTEGER NOT NULL DEFAULT 0;
CREATE TABLE course_chapters (
  chapter_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id INTEGER NOT NULL REFERENCES courses(course_id) ON DELETE CASCADE,
  title VARCHAR(255) NOT NULL,
  order_index INTEGER NOT NULL
);
ALTER TABLE lessons ADD COLUMN chapter_id INTEGER REFERENCES course_chapters(chapter_id) ON DELETE SET NULL;
CREATE INDEX idx_chapters_course ON course_chapters(course_id, order_index);
CREATE INDEX idx_lessons_chapter ON lessons(chapter_id);
CREATE TABLE lesson_assignments (
  assignment_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lesson_id INTEGER NOT NULL UNIQUE REFERENCES lessons(lesson_id) ON DELETE CASCADE,
  title VARCHAR(255) NOT NULL,
  instructions TEXT NOT NULL,
  published BOOLEAN NOT NULL DEFAULT FALSE,
  revision INTEGER NOT NULL DEFAULT 1
);
CREATE TABLE assignment_submissions (
  submission_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  assignment_id INTEGER NOT NULL REFERENCES lesson_assignments(assignment_id) ON DELETE CASCADE,
  student_id INTEGER NOT NULL REFERENCES users(user_id),
  submission_key VARCHAR(36) NOT NULL,
  request_hash VARCHAR(64) NOT NULL,
  assignment_revision INTEGER NOT NULL,
  assignment_title VARCHAR(255) NOT NULL,
  assignment_instructions TEXT NOT NULL,
  answer TEXT NOT NULL,
  file_name VARCHAR(160),
  media_type VARCHAR(80),
  file_content BYTEA,
  submitted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  score INTEGER CHECK (score BETWEEN 0 AND 100),
  feedback TEXT,
  graded_by INTEGER REFERENCES users(user_id),
  graded_at TIMESTAMP,
  grade_revision INTEGER NOT NULL DEFAULT 0,
  UNIQUE (assignment_id, student_id)
);
CREATE INDEX idx_assignment_submissions ON assignment_submissions(assignment_id, submission_id);
CREATE INDEX idx_payments_confirmed_report ON payments(status, confirmed_at, course_id);
CREATE INDEX idx_enrollments_date_report ON enrollments(enrollment_date, course_id);
