CREATE TABLE weekly_learning_goals (
  student_id INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  week_start DATE NOT NULL,
  lesson_target INTEGER NOT NULL CHECK (lesson_target BETWEEN 1 AND 50),
  dashboard_reminder BOOLEAN NOT NULL DEFAULT TRUE,
  revision INTEGER NOT NULL DEFAULT 1,
  PRIMARY KEY (student_id, week_start)
);
CREATE TABLE learning_completions (
  student_id INTEGER NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
  lesson_id INTEGER NOT NULL,
  completed_at TIMESTAMP NOT NULL,
  PRIMARY KEY (student_id, lesson_id)
);
INSERT INTO learning_completions (student_id,lesson_id,completed_at)
SELECT e.student_id,p.lesson_id,MIN(p.completed_at)
FROM lesson_progress p JOIN enrollments e ON e.enrollment_id=p.enrollment_id
WHERE p.is_completed=TRUE AND p.completed_at IS NOT NULL
GROUP BY e.student_id,p.lesson_id;
CREATE INDEX idx_learning_completions_week ON learning_completions(student_id,completed_at);
CREATE TABLE audit_logs (
  audit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  occurred_at TIMESTAMP NOT NULL,
  actor_id INTEGER REFERENCES users(user_id) ON DELETE SET NULL,
  actor_username VARCHAR(100) NOT NULL,
  actor_role VARCHAR(20) NOT NULL,
  action VARCHAR(40) NOT NULL,
  target_type VARCHAR(20) NOT NULL,
  target_id INTEGER NOT NULL,
  target_name VARCHAR(255) NOT NULL,
  before_value VARCHAR(100) NOT NULL,
  after_value VARCHAR(100) NOT NULL
);
CREATE INDEX idx_audit_time ON audit_logs(occurred_at,audit_id);
CREATE INDEX idx_audit_action_time ON audit_logs(action,occurred_at);
