CREATE TABLE IF NOT EXISTS users (
 user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 username VARCHAR(255) NOT NULL UNIQUE, password_hash VARCHAR(255) NOT NULL,
 email VARCHAR(255) NOT NULL UNIQUE, full_name VARCHAR(255) NOT NULL,
 role VARCHAR(255) NOT NULL CHECK (role IN ('ADMIN','TEACHER','STUDENT')),
 is_active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMP, updated_at TIMESTAMP
);
CREATE TABLE IF NOT EXISTS courses (
 course_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 title VARCHAR(255) NOT NULL, description TEXT, teacher_id INTEGER NOT NULL REFERENCES users(user_id),
 price NUMERIC(10,2) DEFAULT 0 CHECK (price >= 0), duration_hours INTEGER CHECK (duration_hours > 0),
 status VARCHAR(20) NOT NULL, created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL
);
CREATE TABLE IF NOT EXISTS lessons (
 lesson_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 course_id INTEGER NOT NULL REFERENCES courses(course_id), title VARCHAR(255) NOT NULL,
 content_url VARCHAR(500), text_content TEXT, order_index INTEGER NOT NULL CHECK (order_index > 0),
 is_published BOOLEAN NOT NULL DEFAULT FALSE, created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL
);
CREATE TABLE IF NOT EXISTS enrollments (
 enrollment_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 student_id INTEGER NOT NULL REFERENCES users(user_id), course_id INTEGER NOT NULL REFERENCES courses(course_id),
 enrollment_date TIMESTAMP NOT NULL, status VARCHAR(20) NOT NULL,
 completion_date TIMESTAMP, progress_percentage NUMERIC(5,2) DEFAULT 0 CHECK (progress_percentage BETWEEN 0 AND 100)
);
CREATE TABLE IF NOT EXISTS lesson_progress (
 progress_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 enrollment_id INTEGER NOT NULL REFERENCES enrollments(enrollment_id), lesson_id INTEGER NOT NULL REFERENCES lessons(lesson_id),
 is_completed BOOLEAN NOT NULL DEFAULT FALSE, completed_at TIMESTAMP, last_accessed_at TIMESTAMP NOT NULL
);
CREATE TABLE IF NOT EXISTS payments (
 payment_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 student_id INTEGER NOT NULL REFERENCES users(user_id), course_id INTEGER NOT NULL REFERENCES courses(course_id),
 amount NUMERIC(10,2) NOT NULL CHECK (amount > 0), status VARCHAR(20) NOT NULL,
 transfer_note VARCHAR(50) UNIQUE, created_at TIMESTAMP NOT NULL, confirmed_at TIMESTAMP,
 confirmed_by INTEGER REFERENCES users(user_id)
);
CREATE TABLE IF NOT EXISTS reviews (
 review_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 course_id INTEGER NOT NULL REFERENCES courses(course_id), student_id INTEGER NOT NULL REFERENCES users(user_id),
 rating INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5), comment TEXT, created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL
);
CREATE TABLE IF NOT EXISTS notifications (
 notification_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 user_id INTEGER NOT NULL REFERENCES users(user_id), message TEXT NOT NULL,
 type VARCHAR(50), target_url VARCHAR(500), is_read BOOLEAN NOT NULL DEFAULT FALSE, created_at TIMESTAMP NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_enrollment_student_course ON enrollments(student_id, course_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_progress_enrollment_lesson ON lesson_progress(enrollment_id, lesson_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_review_student_course ON reviews(student_id, course_id);
CREATE INDEX IF NOT EXISTS ix_lesson_course ON lessons(course_id, order_index);
CREATE INDEX IF NOT EXISTS ix_payment_student ON payments(student_id, course_id, status);
CREATE INDEX IF NOT EXISTS ix_notification_user ON notifications(user_id, created_at);
