ALTER TABLE users ADD COLUMN IF NOT EXISTS auth_version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE courses ADD COLUMN IF NOT EXISTS category VARCHAR(255) NOT NULL DEFAULT 'Lập trình';
ALTER TABLE courses ADD COLUMN IF NOT EXISTS level VARCHAR(255) NOT NULL DEFAULT 'Cơ bản';
ALTER TABLE courses ADD COLUMN IF NOT EXISTS learning_outcomes TEXT;
