CREATE TABLE lesson_questions (
    question_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lesson_id INTEGER NOT NULL REFERENCES lessons(lesson_id) ON DELETE CASCADE,
    student_id INTEGER NOT NULL REFERENCES users(user_id),
    body TEXT NOT NULL,
    answer TEXT,
    answered_by INTEGER REFERENCES users(user_id),
    answered_at TIMESTAMP,
    is_hidden BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_question_lesson_visible ON lesson_questions(lesson_id, is_hidden, question_id DESC);
