CREATE TABLE lesson_quiz_versions (
    quiz_version_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lesson_id INTEGER NOT NULL REFERENCES lessons(lesson_id) ON DELETE CASCADE,
    revision INTEGER NOT NULL,
    title VARCHAR(255) NOT NULL,
    pass_percentage INTEGER NOT NULL CHECK (pass_percentage BETWEEN 1 AND 100),
    is_published BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (lesson_id, revision)
);
CREATE TABLE quiz_questions (
    quiz_question_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quiz_version_id INTEGER NOT NULL REFERENCES lesson_quiz_versions(quiz_version_id) ON DELETE CASCADE,
    order_index INTEGER NOT NULL,
    prompt TEXT NOT NULL,
    option_a VARCHAR(1000) NOT NULL,
    option_b VARCHAR(1000) NOT NULL,
    option_c VARCHAR(1000) NOT NULL,
    option_d VARCHAR(1000) NOT NULL,
    correct_index INTEGER NOT NULL CHECK (correct_index BETWEEN 0 AND 3),
    explanation TEXT NOT NULL,
    UNIQUE (quiz_version_id, order_index)
);
CREATE TABLE quiz_attempts (
    attempt_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quiz_version_id INTEGER NOT NULL REFERENCES lesson_quiz_versions(quiz_version_id) ON DELETE CASCADE,
    student_id INTEGER NOT NULL REFERENCES users(user_id),
    submission_key VARCHAR(36) NOT NULL,
    correct_count INTEGER NOT NULL,
    question_count INTEGER NOT NULL,
    score INTEGER NOT NULL,
    passed BOOLEAN NOT NULL,
    submitted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (student_id, submission_key)
);
CREATE TABLE quiz_answers (
    answer_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attempt_id INTEGER NOT NULL REFERENCES quiz_attempts(attempt_id) ON DELETE CASCADE,
    quiz_question_id INTEGER NOT NULL REFERENCES quiz_questions(quiz_question_id) ON DELETE CASCADE,
    selected_index INTEGER NOT NULL CHECK (selected_index BETWEEN 0 AND 3),
    UNIQUE (attempt_id, quiz_question_id)
);
CREATE INDEX idx_quiz_history ON quiz_attempts(student_id, quiz_version_id, attempt_id DESC);
CREATE INDEX idx_quiz_attempt_version ON quiz_attempts(quiz_version_id);
